[package]
name = "warp-packer"
version = "0.3.0"
authors = ["Diego Giagio <diego@giagio.com>"]

[dependencies]
clap = "2.32.0"
dirs = "1.0.4"
tempdir = "0.3.7"
flate2 = "1.0"
tar = "0.4"
lazy_static = "1.1.0"
#TODO: reqwest contains unstable libraries
#reqwest = "0.9.2"
